# Generated by Django 5.0.6 on 2024-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order_item",
            name="count",
            field=models.IntegerField(),
        ),
    ]
