# Generated by Django 5.0.6 on 2024-07-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_item_price_alter_order_item_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="stock_quantity",
            field=models.IntegerField(),
        ),
    ]
