# Generated by Django 5.0.6 on 2024-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="IPRG", max_length=30),
        ),
    ]
