# Generated by Django 5.0.6 on 2024-07-05 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_item_order_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="item",
            new_name="items",
        ),
    ]
