# Generated by Django 5.0.6 on 2024-07-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_item_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.TextField(
                choices=[("IPRG", "In progress"), ("DONE", "Done")],
                default="IPRG",
                max_length=128,
            ),
        ),
    ]
