# Generated by Django 5.0.6 on 2024-07-03 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_adress_address_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adress",
            new_name="Address",
        ),
        migrations.AlterModelTable(
            name="address",
            table="address",
        ),
    ]
