# Generated by Django 5.0.6 on 2024-07-03 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_rename_adress_address_alter_address_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_id",
        ),
    ]
